version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: nodevaultscdproject-mongo
    restart: always
    volumes:
      - nodevault-data:/data/db
    networks:
      - nodevault-network

  backend:
    image: nodevault-backendscdproject:1.0   # <-- Your backend image
    container_name: nodevault-backendscdproject
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - nodevault-network

networks:
  nodevault-network:
    driver: bridge
    internal: true   # PRIVATE network (same requirement as Part 5)

volumes:
  nodevault-data:
